version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysite_web
    ports:
      - "8000:8000"  
    volumes:
      - .:/app        
    environment:
      - DJANGO_SETTINGS_MODULE=mysite.settings  
      - PYTHONUNBUFFERED=1                     
    command: >
      sh -c "cd /app/mysite &&
             gunicorn mysite.wsgi:application --bind 0.0.0.0:8000"

  nginx:
    image: nginx:1.25-alpine 
    container_name: mysite_nginx
    ports:
      - "81:80"  # 80 to 8000
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # volume config file
      - ./static:/app/static  # volume static files
      - ./media:/app/media  # volume media files
    depends_on:
      - web  # depends on web 



# To run the docker-compose file, use the following command:
#docker-compose up --build  